## Avanço Lista de Documentos da Sulzer:

### Carregar LD e Report do Integra com as informações a serem avaliadas:

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# pd.set_option('mode.chained_assignment', None)
# Nome dos arquivos para carregar no Pandas

ld_file = 'C:\\Users\\elxy\\Documents\\Codigos\\Python\\P84_85\\I-LD-3010.2S-1251-911-SJA-001_0.xlsx'
ld_file_VDA = 'C:\\Users\\elxy\\Documents\\Codigos\\Python\\P84_85\\VDA_original.xlsx'
integra_report = 'C:\\Users\\elxy\\Documents\\Codigos\\Python\\P84_85\\RE-General Query - Technical Engineering Documents-0000000040.xlsx'

df_LD = pd.read_excel(ld_file, sheet_name="VDRL")
df_VDA = pd.read_excel(ld_file_VDA, sheet_name="VDRL")
df_integra = pd.read_excel(integra_report, sheet_name="DADOS")

c:\Users\ELXY\Documents\Codigos\Python\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
c:\Users\ELXY\Documents\Codigos\Python\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

#### Pre-processamento dos dados

In [36]:
df_LD.columns = df_LD.iloc[6]
df_LD = df_LD.iloc[7:]

df_VDA.columns = df_VDA.iloc[6]
df_VDA = df_VDA.iloc[7:]

df_LD.rename(columns = {"CLIENT DOCUMENT NUMBER":"CLIENT_DOCUMENT", 
                        "VENDOR DOCUMENT NUMBER":"VENDOR_DOCUMENT", 
                        "DOCUMENT TITLE": "DOCUMENT_TITLE", "PLANNED DATE": "PLANNED_DATE"}, inplace = True)
df_VDA.rename(columns = {"Have a comment?":"Have_a_comment", "CLIENT DOCUMENT NUMBER":"CLIENT_DOCUMENT", 
                        "VENDOR DOCUMENT NUMBER":"VENDOR_DOCUMENT", 
                        "DOCUMENT TITLE": "DOCUMENT_TITLE", "PLANNED DATE": "PLANNED_DATE"}, inplace = True)

df_integra.rename(columns = {"CREATION DATE":"CREATION_DATE"}, inplace = True)

colunas_para_manter = ["CLIENT_DOCUMENT", "VENDOR_DOCUMENT", "DOCUMENT_TITLE", "ORIGINATOR ", "PLANNED_DATE"]  # Lista de colunas para  manter
df_LD.drop(columns=[col for col in df_LD.columns if col not in colunas_para_manter], inplace = True)
df_LD.reset_index(drop=True, inplace = True)

colunas_para_manter_VDA = ["Have_a_comment", "Discipline", "CLIENT_DOCUMENT", "VENDOR_DOCUMENT", "DOCUMENT_TITLE", "ORIGINATOR ", "PLANNED_DATE"]  # Lista de colunas para  manter
df_VDA.drop(columns=[col for col in df_VDA.columns if col not in colunas_para_manter_VDA], inplace = True)
df_VDA.reset_index(drop=True, inplace = True)

# Remover as duas últimas colunas 
df_LD = df_LD.iloc[:, :-2]
df_VDA = df_VDA.iloc[:, :-2]

### Mostra os dados

In [37]:
df_VDA.head(10)

6,Have_a_comment,Discipline,CLIENT_DOCUMENT,VENDOR_DOCUMENT,DOCUMENT_TITLE,PLANNED_DATE
0,NaN,NaN,I-CE-3010.2S-1251-856-SJA-001,ICC1005579960040-01,CALIBRATION CERTIFICATES - INSTRUMENT FOR B-12...,2025-12-05 00:00:00
1,NaN,NaN,I-CE-3010.2S-1251-856-SJA-101,ICC1005579960010-01,CALIBRATION CERTIFICATES - INSTRUMENT FOR B-12...,2025-12-05 00:00:00
2,NaN,NaN,I-CE-3010.2S-1251-856-SJA-201,ICC1005579960090-01,CALIBRATION CERTIFICATES - INSTRUMENT FOR B-12...,2025-12-05 00:00:00
3,NaN,NaN,I-CE-3010.2S-1251-910-SJA-001,QAC1005579960010-01,QUALITY MANAGEMENT SYSTEM CERTIFICATE FOR ALL ...,2025-01-06 00:00:00
4,NaN,NaN,I-CE-3010.2S-1251-974-SJA-001,QTR1005579960040-01,CERTIFICATES AND REPORTS FOR PUMPS AND ACCESSO...,2025-12-05 00:00:00
5,NaN,NaN,I-CE-3010.2S-1251-974-SJA-002,QTR1005579960040-02,CERTIFICATES AND REPORTS FOR MECHANICAL SEAL F...,2025-12-05 00:00:00
6,NaN,NaN,I-CE-3010.2S-1251-974-SJA-003,QTR1005579960040-03,CERTIFICATES AND REPORTS FOR ELECTRICAL MOTOR ...,2025-12-05 00:00:00
7,NaN,NaN,I-CE-3010.2S-1251-974-SJA-101,QTR1005579960010-01,CERTIFICATES AND REPORTS FOR PUMPS AND ACCESSO...,2025-12-05 00:00:00
8,NaN,NaN,I-CE-3010.2S-1251-974-SJA-102,QTR1005579960010-02,CERTIFICATES AND REPORTS FOR MECHANICAL SEAL F...,2025-12-05 00:00:00
9,NaN,NaN,I-CE-3010.2S-1251-974-SJA-103,QTR1005579960010-03,CERTIFICATES AND REPORTS FOR ELECTRICAL MOTOR ...,2025-12-05 00:00:00

### Itera o df_integra e o df_VDA inclui novas colunas no dataframe df_LD. Compara o df_VDA com o df_LD para buscar informação perdida de Have_a_comment e Discipline.

In [38]:
for row in df_integra.itertuples():
    codigo = row.CODE
    descricao = row.TITLE
    dt_criacao = row.CREATION_DATE
    
    # usando a função .loc para atualizar os valores
    # df_escopo.loc[(df_escopo['PKG_DESCRIPTION'] == pkg_description) & (df_escopo['item_tag'] == item_tag) , "PO_Number"] = pkg_engineer
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "CODE"] = codigo
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "TITLE"] = descricao
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "CREATION_DATE"] = dt_criacao

for row in df_VDA.itertuples():
    have_comment = row.Have_a_comment
    discipline = row.Discipline
    codigo = row.CLIENT_DOCUMENT
    descricao = row.DOCUMENT_TITLE

    # avalia se tem o mesmo código de documento:
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "CLIENT_DOCUMENT_VDA_cod"] = codigo
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "DOCUMENT_TITLE_VDA_cod"] = descricao
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "Have_a_comment_cod"] = have_comment
    df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "Discipline_cod"] = discipline

    df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "CLIENT_DOCUMENT_VDA_desc"] = codigo
    df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "DOCUMENT_TITLE_VDA_desc"] = descricao
    df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "Have_a_comment_desc"] = have_comment
    df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "Discipline_desc"] = discipline

# display(df_LD)

C:\Users\ELXY\AppData\Local\Temp\ipykernel_14340\1431833441.py:21: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'YES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "Have_a_comment_cod"] = have_comment
C:\Users\ELXY\AppData\Local\Temp\ipykernel_14340\1431833441.py:22: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UN dynamic' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_LD.loc[(df_LD['CLIENT_DOCUMENT'] == codigo), "Discipline_cod"] = discipline
C:\Users\ELXY\AppData\Local\Temp\ipykernel_14340\1431833441.py:26: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'YES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "Have_a_comment_desc"] = have_comment
C:\Users\ELXY\AppData\Local\Temp\ipykernel_14340\1431833441.py:27: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'UN dynamic' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_LD.loc[(df_LD['DOCUMENT_TITLE'] == descricao), "Discipline_desc"] = discipline

### Consolida o Have_a_comment e Discipline numa unica coluna.

In [42]:
# Cria e consolida a coluna 'Have_a_comment' a partir de uma das duas colunas "Have_a_comment_cod" ou "Have_a_comment_desc"
df_LD['Have_a_comment'] = np.where(df_LD['Have_a_comment_cod'].notnull(),
                                 df_LD['Have_a_comment_cod'],
                                 df_LD['Have_a_comment_desc'])

# Cria e consolida a coluna 'Discipline' a partir de uma das duas colunas "Discipline_cod" ou "Discipline_desc"
df_LD['Discipline'] = np.where(df_LD['Discipline_cod'].notnull(),
                                 df_LD['Discipline_cod'],
                                 df_LD['Discipline_desc'])

### Realiza o agrupamento das informações

In [40]:
# Group by 'PLANNED_DATE' and count documents
grouped_df = df_LD.groupby('PLANNED_DATE')
count_per_date = pd.DataFrame(grouped_df.size())
# print(type(count_per_date))
count_per_date.reset_index(drop=False, inplace = True)

#display(grouped_df)

# print("Valores Agrupados - DataFrame df_grouped_prefix:")
display(count_per_date)

   PLANNED_DATE   0
0    2024-10-25  19
1    2024-10-30   4
2    2024-11-13   8
3    2024-11-27  16
4    2024-12-02   5
5    2024-12-11  17
6    2024-12-27  21
7    2025-01-06   7
8    2025-01-08   2
9    2025-01-13   3
10   2025-01-15   1
11   2025-01-22   9
12   2025-01-24  15
13   2025-01-28   6
14   2025-02-05   6
15   2025-02-19  49
16   2025-03-25   6
17   2025-03-26   9
18   2025-03-31   3
19   2025-04-16   9
20   2025-04-30  19
21   2025-05-05  12
22   2025-05-29   6
23   2025-09-30   3
24   2025-12-05  39
25   2025-12-12   3
26   2026-01-06   3
27   2026-01-10   3
28   2026-03-04   3
29   2026-03-20   3

### Salva DataFrame num arquivo excel

In [ ]:
avanco_ld_cesar = 'C:\\Users\\elxy\\Documents\\Codigos\\Python\\P84_85\\Avanco_LD_cesar.xlsx'

with pd.ExcelWriter(avanco_ld_cesar) as writer:
    df_LD.to_excel(writer, sheet_name='LD', index=False)
    count_per_date.to_excel(writer, sheet_name='emissao', index=False)
print(f'Arquivo {avanco_ld_cesar} salvo em: ', Path.cwd())

Arquivo C:\Users\elxy\Documents\Codigos\Python\P84_85\Avanco_LD_cesar.xlsx salvo em:  c:\Users\ELXY\Documents\Codigos\Python\P84_85

: